### ISSUE TITLE
Missing effect op should raise error

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6084] opened 2023-06-08 10:43 UTC
I would expect this to give an error:

```
eff Print {
    pub def print(): Unit
}

eff Throw {
    pub def thrw(): Unit
}

def f(): Unit \ {Print, Throw} = 
    do Print.print();
    do Throw.thrw()

def g(): Unit = 
    def _unused() = 
        try {
            f()
        } with Print {
            // def print(_k) = () // missing
        };
    ()

```

**Comment by JonathanStarup** [comment] 2024-09-23 20:20
This example now fails because the with block cannot be empty, but the general issue remains

Duplicate of https://github.com/flix/flix/issues/7148

**Closed by JonathanStarup** 2024-09-23 20:20 UTC
Labels: bug, A: missing check
