### ISSUE TITLE
Compilation through intellij IDEA seems broken

### ISSUE THREAD

**Issue by nicdard** [flix/flix#2894] opened 2021-12-22 17:56 UTC
```
/usr/lib/jvm/java-1.14.0-openjdk-amd64/bin/java -javaagent:/opt/idea-IU-212.5080.55/lib/idea_rt.jar=42455:/opt/idea-IU-212.5080.55/bin -Dfile.encoding=UTF-8 -classpath /home/nicola/Documents/projects/flix/out/production/flix:/home/nicola/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.13.6.jar:/home/nicola/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.13.6.jar:/home/nicola/Documents/projects/flix/lib/org.jline-3.5.1.jar:/home/nicola/Documents/projects/flix/lib/scala.xml-1.2.0.jar:/home/nicola/Documents/projects/flix/lib/shapeless-2.3.3.jar:/home/nicola/Documents/projects/flix/lib/org.parboiled-2.2.1.jar:/home/nicola/Documents/projects/flix/lib/org.scalactic-3.0.8.jar:/home/nicola/Documents/projects/flix/lib/org.scalatest-3.0.8.jar:/home/nicola/Documents/projects/flix/lib/org.json4s-ast-3.5.5.jar:/home/nicola/Documents/projects/flix/lib/org.json4s-core-3.5.5.jar:/home/nicola/Documents/projects/flix/lib/org.objectweb.asm-9.2.jar:/home/nicola/Documents/projects/flix/lib/com.github.scopt-3.7.1.jar:/home/nicola/Documents/projects/flix/lib/org.json4s-native-3.5.5.jar:/home/nicola/Documents/projects/flix/lib/org.java_websocket-1.3.9.jar:/home/nicola/Documents/projects/flix/lib/scala.collection.parallel-0.2.0.jar ca.uwaterloo.flix.Main
     __   _   _
    / _| | | (_)            Welcome to Flix v0.25.0
   | |_  | |  _  __  __
   |  _| | | | | \ \/ /     Enter a command and hit return.
   | |   | | | |  >  <      Type ':help' for more information.
   |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.
      
 [/] [JvmBackend]                                                               Exception in thread "main" java.lang.ExceptionInInitializerError
	at ca.uwaterloo.flix.language.phase.jvm.BackendObjType.$init$(BackendObjType.scala:42)
	at ca.uwaterloo.flix.language.phase.jvm.BackendObjType$Record$.<clinit>(BackendObjType.scala:134)
	at ca.uwaterloo.flix.language.phase.jvm.GenRecordInterface$.gen(GenRecordInterface.scala:30)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$2(JvmBackend.scala:125)
	at ca.uwaterloo.flix.api.Flix.subphase(Flix.scala:525)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$1(JvmBackend.scala:44)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:487)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:36)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:31)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:48)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:73)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:456)
	at ca.uwaterloo.flix.runtime.shell.Shell.ca$uwaterloo$flix$runtime$shell$Shell$$execReload(Shell.scala:382)
	at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:101)
	at ca.uwaterloo.flix.Main$.main(Main.scala:175)
	at ca.uwaterloo.flix.Main.main(Main.scala)
Caused by: java.lang.NullPointerException
	at ca.uwaterloo.flix.language.phase.jvm.BackendObjType$RecordEmpty$.<clinit>(BackendObjType.scala:119)
	... 20 more

Process finished with exit code 1
```

This is the output from the compiler when I try to compile it through Intellij IDEA, while compilation and tests through gradle is working normally

The problem is given by a `NullPointerException` which is triggered apparently in `BackendObjType` line 119 in the current master branch (last commit: 43c58c4 Add foldRightL - part 2 (#2889))

**Comment by nicdard** [comment] 2021-12-22 17:58
I think the change was introduced by: #2891

**Comment by magnus-madsen** [comment] 2021-12-22 18:13
I reverted #2891 -- does that resolve the issue?

**Comment by nicdard** [comment] 2021-12-22 18:17
Yes, thanks!

**Comment by JonathanStarup** [comment] 2021-12-23 18:20
@nicdard what was the program?

**Comment by magnus-madsen** [comment] 2021-12-23 18:45
And did it only happen in interactive mode?

**Comment by nicdard** [comment] 2021-12-23 22:28
So yes, I just started the compiler (no program actually)

**Comment by JonathanStarup** [comment] 2021-12-26 15:58
@magnus-madsen my code was sensitive to static object initialization in a way that is only triggered by this way of running the compiler. It seems most of my recent subtle bugs support some flix principle

**Comment by JonathanStarup** [comment] 2021-12-26 16:03
The problem is fixed by correcting the object order in the file and then swapping case order!?
```
sealed trait BackendObjType {
  val jvmName: JvmName = this match {
    ....
    case BackendObjType.RecordEmpty => JvmName(RootPackage, mkName(s"RecordEmpty"))
    case BackendObjType.RecordExtend(_, value, _) => JvmName(RootPackage, mkName("RecordExtend", value))
    case BackendObjType.Record => JvmName(RootPackage, s"IRecord${Flix.Delimiter}")
  ....
```
The lowest case has the be the top case of these three to avoid null. I have no clue why that is the case. It might the the way scala interprets trait val's and pattern matches?

**Comment by magnus-madsen** [comment] 2021-12-26 16:17
`val`s are a form of global state, right? They are start out null and are then initialized. If you have recursive dependencies between them then its a problem. This is why I tend to avoid vals.

**Comment by magnus-madsen** [comment] 2021-12-26 16:18
Clever use of `lazy val` either solves the problem or makes it infinitely worse.

**Comment by magnus-madsen** [comment] 2021-12-26 16:19
Probably `jvmName` should be define on each type?

**Comment by JonathanStarup** [comment] 2021-12-26 20:34
i think i will make everything def to make sure it is correct, performance can then come later if relevant.

**Comment by JonathanStarup** [comment] 2021-12-26 20:34
> Clever use of `lazy val` either solves the problem or makes it infinitely worse. 

that is also my experience 😄

**Comment by JonathanStarup** [comment] 2021-12-29 15:35
@magnus-madsen I think this can be closed again

**Closed** 2021-12-29 15:49 UTC
