### ISSUE TITLE
New Solver - Negation - bug or invalid program?

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#1973] opened 2021-05-28 20:30 UTC
I have a program that worked with the old solver but crashes with the new solver - I'm not 100% sure that its use of negation is valid but a runtime crash is a bit harsh...

The program uses negation assert a missing `StringValue` and assign "NONE" to location - the query answer `Location` should provide a result for all three keys ("x3" should be "NONE"):

~~~

rel StringValue(id: String, field: String, value: String)
rel Key(id: String)
rel Location(id: String, value: String)

def locations(): #{ Location, Key, StringValue | r } = solve #{
    StringValue("x1", "LOCATION", "Europe").
    StringValue("x2", "LOCATION", "Bermuda").
    Key("x1").
    Key("x2").
    Key("x3").

    Location(key, loc) :- 
        Key(key),
        StringValue(key, "LOCATION", loc).

    Location(key, "NONE") :- 
        Key(key),
        not StringValue(key, "LOCATION", _).
}


def main(_args: Array[String]): Int32 & Impure = 
    test01();
    0

def test01(): Unit & Impure =     
    query locations() select (x1, x2) from Location(x1, x2) 
        |> Array.foreach(println)
        
~~~        

I've added more output to Fixpoint.Compiler.flix to print the atom that generates the error:

~~~

    def augmentBody(body: Array[BodyPredicate[v]]): Array[(BodyPredicate[v], RowVar)] with ToString[v] =
        Array.mapWithIndex(atom -> i -> match atom {
            case BodyAtom(predSym, _, Polarity.Positive, _) => (atom, RowVar.Named("${predSym}$${i}"))
            case _ => (atom, RowVar.Named("IfYouSeeThisYouFoundABug - ```${atom}```"))
        }, body) as & Pure
        
~~~        

The program trace is: 

~~~

✓ Reader                                    10.7ms
✓ Parser                                  4230.4ms
✓ Weeder                                  1410.3ms
✓ Namer                                   1193.9ms
✓ Resolver                                1562.7ms
✓ Typer                                   3751.1ms
✓ Instances                                 56.5ms
✓ Stratifier                               148.6ms
    Compute Dependency Graph             (  46.1ms)
    Compute Stratification               (  98.5ms)
✓ PatternExhaustiveness                    555.8ms
✓ Redundancy                               487.0ms
✓ Safety                                    42.6ms
✓ Documentor                                 0.0ms
✓ Lowering                                 131.7ms
✓ Monomorph                                447.3ms
✓ Simplifier                               225.2ms
✓ ClosureConv                              416.6ms
✓ LambdaLift                               163.7ms
✓ Tailrec                                   19.3ms
✓ Optimizer                                 76.1ms
✓ TreeShaker                                90.7ms
✓ VarNumbering                              17.2ms
✓ Finalize                                 230.2ms
✓ Eraser                                   186.1ms
✓ JvmBackend                              6826.5ms
    CodeGen                              (2205.8ms)
    WriteClasses                         (4025.0ms)
    LoadClasses                          ( 411.9ms)
    LoadMethods                          ( 173.0ms)
Compiled 40,164 lines in 22.3 sec. (1,803 lines/sec).
********************************************************************************
**
**  BUG: Illegal term IfYouSeeThisYouFoundABug - ```not StringValue(key, LOCATION, _)```[2]
**
********************************************************************************

Hole '?panic' at Prelude.flix:120:5

HoleError{hole='?panic', location=flix.runtime.ReifiedSourceLocation@606a3075}
	at Def$bug!$191254.invoke(Unknown Source)
	at Array.Def$initHelper$191281.invoke(Unknown Source)
	at Array.Def$init$190633.invoke(Unknown Source)
	at Fixpoint.Clo$evalBoolExp$192254$224355.invoke(Unknown Source)
	at List.Def$forall$193300.invoke(Unknown Source)
	at Fixpoint.Def$evalOp$192232.invoke(Unknown Source)
	at RedBlackTree.Def$foreach$191275.invoke(Unknown Source)
	at RedBlackTree.Def$foreach$191275.invoke(Unknown Source)
	at Array.Def$foreachHelper$193296.invoke(Unknown Source)
	at Fixpoint.Def$interpretWithDatabase$190689.invoke(Unknown Source)
	at Fixpoint.Def$solveWithStratification$189592.invoke(Unknown Source)
	at Def$locations$184894.invoke(Unknown Source)
	at Def$test01.invoke(Unknown Source)
	at Def$main.invoke(Unknown Source)
	at Ns.m_main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:263)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2(JvmBackend.scala:224)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2$adapted(JvmBackend.scala:222)
	at ca.uwaterloo.flix.Main$.main(Main.scala:196)
	at ca.uwaterloo.flix.Main.main(Main.scala)

Process finished with exit code 1

~~~

With the old solver, the program runs as I expect...

~~~


rel StringValue(id: String, field: String, value: String)
rel Key(id: String)
rel Location(id: String, value: String)

def locations(): #{ Location, Key, StringValue | r } = solve #{
    StringValue("x1", "LOCATION", "Europe").
    StringValue("x2", "LOCATION", "Bermuda").
    Key("x1").
    Key("x2").
    Key("x3").

    Location(key, loc) :- 
        Key(key),
        StringValue(key, "LOCATION", loc).

    Location(key, "NONE") :- 
        Key(key),
        not StringValue(key, "LOCATION", _).
}


def main(_args: Array[String]): Int32 & Impure = 
    test01();
    0

def test01(): Unit & Impure =     
    (project Location locations())
        |> unsafeToString
        |> println
        
~~~

Output:

~~~

✓ Reader                                    33.0ms
✓ Parser                                  2764.1ms
✓ Weeder                                   881.7ms
✓ Namer                                   1315.5ms
✓ Resolver                                1790.4ms
✓ Typer                                   3931.3ms
✓ Instances                                 68.5ms
✓ Stratifier                               375.9ms
    Compute Dependency Graph             ( 132.5ms)
    Compute Stratification               ( 135.5ms)
✓ PatternExhaustiveness                    680.0ms
✓ Redundancy                              1090.3ms
✓ Safety                                   174.7ms
✓ Documentor                                 0.0ms
✓ Monomorph                                673.6ms
✓ Simplifier                              4418.1ms
✓ ClosureConv                             1084.4ms
✓ LambdaLift                              2640.5ms
✓ Tailrec                                   18.7ms
✓ Optimizer                                265.6ms
✓ TreeShaker                               173.8ms
✓ VarNumbering                             147.2ms
✓ Finalize                                1553.9ms
✓ Eraser                                  2139.8ms
✓ JvmBackend                              5140.4ms
    CodeGen                              (2459.0ms)
    WriteClasses                         (2583.6ms)
    LoadClasses                          (  38.3ms)
    LoadMethods                          (  14.2ms)
Compiled 36,859 lines in 31.4 sec. (1,175 lines/sec).
Solved in 56 msec. (init: 23 msec, readers: 11 msec, writers: 18 msec)
Initial Facts: 5. Total Facts: 8.
Throughput: 140 facts per second.
Location
------+---------
 col0 | col1    
------+---------
 x3   | NONE    
------+---------
 x1   | Europe  
------+---------
 x2   | Bermuda 
------+---------



Process finished with exit code 0

~~~

Is this a bug with the new solver, or was my program wrong?

**Comment by magnus-madsen** [comment] 2021-05-29 04:42
@bdahse 

Will you take a look?

**Comment by magnus-madsen** [comment] 2021-05-29 04:43
Program looks OK to me.

**Comment by magnus-madsen** [comment] 2021-05-29 19:09
@stephentetley 

This is close to an edge case (w.r.t. something called positively bound variables.). Ill see what we can do.

Meanwhile, I would suggest the following rewrite:

```
    LocationNoCountry(x, y) :- Location(x, y, _).

    Location(key, "NONE") :-
        Key(key),
        not LocationNoCountry(key, "LOCATION").
```

although I understand that it is not great.

**Comment by magnus-madsen** [comment] 2021-05-29 19:26
I am now fairly convinced that this program is illegal because `_` represents an (unnamed) variable that only occurs in a negated atom and such non-positively bounds variables are not allowed. (Note that if you replace `_` by say `foo` Flix already rejects the program). 

The reason for this restriction is subtle and I don't fully understand it yet. However, I do see that disallowing such rules ensure that rules with negation are evaluated efficiently.

I think, in the short term, and pending Benjamin's comment, this should be fixed by rejecting the above program. As a future extension, we can then try to see if there are certain cases (like here) where it can still make sense to allow such non-positively bound variables. 

@stephentetley Could you give an estimate of whether this is just something you need in one rule, or is a common pattern that occur in several places. (I could imagine that it would be useful to write such programs-- at least with wildcards).

**Comment by magnus-madsen** [comment] 2021-05-29 19:27
![image](https://user-images.githubusercontent.com/2287953/120082707-b5229e80-c0c4-11eb-9f9c-43eb7d76a377.png)

![image](https://user-images.githubusercontent.com/2287953/120082709-ba7fe900-c0c4-11eb-9286-ce8a96aa0c4c.png)

**Comment by stephentetley** [comment] 2021-05-29 21:19
Thanks Magnus

I did wonder that the program might not be legal.

The "idiom" of matching on string keys rather than specific typed atoms, I'm using a lot in the modules here:

https://github.com/stephentetley/work-flix/tree/master/src/libs/AssetLib/GenS4/Rules

and the modules in the sub-folder `Characteristics`.

I started with specifically typed atoms, e.g. 

> rel SignalUnit(key: String, unit: String)

> SignalUnit(aibref, "mA")

rather than 

> AibStringValue(aibref, "SIGNAL_UNIT", "mA")

but because there are so many different types, the type of the constraint set quickly became unmanageable.

I'll have to think about solving the problem in a different way.

**Comment by bdahse** [comment] 2021-05-31 16:19
Yeah Magnus is right, the problem is the wildcard in `not StringValue(key, LOCATION, _)`. That atom is compiled into an if-statement: `if (key, "LOCATION", _) notin StringValue then ...` where the wildcard refers to an illegal/invalid term (index 2 of the unbound variable named IfYouSeeThisYouFoundABug). The "bug" is triggered because programs are assumed to be "safe" as in https://github.com/flix/flix/issues/1973#issuecomment-850887176 .

If we want to relax the nonpositively bound var restriction on wildcards, how do we evaluate expressions such as `(key, "LOCATION", _) notin StringValue`? In this particular case we could do a range-query on `StringValue`. But what about `(_, key, "LOCATION") notin StringValue` for a different program? Wouldn't the membership query take O(StringValue) time?

Also, should safety violations be detected at runtime or compile-time?

**Comment by magnus-madsen** [comment] 2021-08-22 06:54
In summary, this minimal example should be rejected by the `Safety` phase:

```
def main(_args: Array[String]) : Int32 & Impure = 
    let p = #{
        A(1, 2).
        B(1) :- not A(1, _).
    };
    query p select x from B(x) |> println;
    0
```

**Comment by bdahse** [comment] 2021-09-19 21:59
Basically the Safety phase (is that new?) should detect wildcards in negative atoms?

**Comment by magnus-madsen** [comment] 2021-09-20 06:04
@bdahse Yes, I believe @JonathanStarup is working on it.

**Comment by JonathanStarup** [comment] 2021-09-23 10:24
In #2351 this now results in:
```
-- Safety Error -------------------------------------------------- examples\misc\test.flix

>> Illegal negatively bound wildcard '_'.

19 |         not StringValue(key, "LOCATION", _).
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             the wildcard occurs in this negated atom.



Compilation failed with 1 error(s).

Process finished with exit code 1
```

**Closed** 2021-09-28 11:38 UTC
Labels: bug
