### ISSUE TITLE
Debate: Replace fold and reduce by monoidal folds and semigroupal reduces

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1682] opened 2021-01-17 17:23 UTC
We currently have the aliases:

```
List.fold -> List.foldLeft
Set.fold -> Set.foldLeft
```

(also for `reduce` afaik).

I would like to *remove* them and instead introduce the names:

```
Foldable.fold (with a monoid)
Reducible.reduce (with a monoid)
```

**Comment by magnus-madsen** [comment] 2021-01-18 16:08
Unless there are objections I want to kill the aliases and reserve the names for monoidal (sp?) folds.

**Comment by stephentetley** [comment] 2021-01-18 20:14
I'd be happy for them to be removed from List, Array, etc. I'm not sure they merited the bias over right folds.

I haven't really looked at Set as the idea "direction" is a bit more abstract, if we know that the set is stored from smallest values to largest values then I'd be happy with having just `foldRight` and `foldLeft` and omitting `fold`.

**Comment by magnus-madsen** [comment] 2021-01-19 07:55
> I haven't really looked at Set as the idea "direction" is a bit more abstract, if we know that the set is stored from smallest values to largest values then I'd be happy with having just `foldRight` and `foldLeft` and omitting `fold`.

Sets are implemented as trees backed by `Order`ed hence we can fold on them :)

**Comment by magnus-madsen** [comment] 2021-01-19 08:01
@esbenbjerre 

Will you go through the following data types:
- Option
- Result
- List / MutList
- Set / MutSet
- Map / MutMap
- Nel

And delete all `fold` and `reduce` operations that are marked as "alias for". (Delete their test cases too).

Then add 

```
def fold[a: Monoid](xs: List[a]): a
```
(Here shown for list).

Then, for `Nel`, also add:

```
def reduce[a: SemiGroup](xs: Nel[a]): a
```

(this requires the semi group TC).

Please also add some tests :)

**Comment by esbenbjerre** [comment] 2021-01-19 10:51
> (this requires the semi group TC).

Sure.
Should I just add a "dummy" `SemiGroup` TC and then we can make it a superclass later when Matthew PR is merged in?

**Comment by magnus-madsen** [comment] 2021-01-19 10:52
> > (this requires the semi group TC).
> 
> Sure.
> Should I just add a "dummy" `SemiGroup` TC and then we can make it a superclass later when Matthew PR is merged in?

Tes

**Comment by esbenbjerre** [comment] 2021-01-19 11:00
> Yes, let us call it "Semigroup". Hmm or should it be "SemiGroup".

I see that people spell it both semigroup and semi-group, but it seems semigroup is most common. I think we should go for `Semigroup `.

**Comment by magnus-madsen** [comment] 2021-01-19 20:59
> 
> 
> Is it fine that `fold` calls `Foldable.fold`?

Yes, I think so.

**Comment by esbenbjerre** [comment] 2021-01-20 07:53
I don't think it is possible to add a `Foldable` instance for `Result` as of now. The issue is the same as with `Map`.

**Comment by magnus-madsen** [comment] 2021-01-20 07:53
Yes. We should open a ticket.

**Comment by magnus-madsen** [comment] 2021-01-20 07:53
But please remove the aliases anyway.

**Closed** 2021-01-20 10:10 UTC
Labels: language-design, student-programmer
