### ISSUE TITLE
VSCode: Renaming a file causes NameErrors

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3186] opened 2022-02-13 19:36 UTC
Appears to be related to incremental compilation

**Comment by JonathanStarup** [comment] 2022-02-16 22:00
I had the bug where it persisted even through closing and opening vscode completely.

**Comment by magnus-madsen** [comment] 2022-02-16 22:06
But restarting VSCode clears out any incremental caches (??)

**Comment by JonathanStarup** [comment] 2022-02-16 22:10
It persists even through restarting my computer.. I have triple checked that the file does not exist. I'm pretty confused

**Comment by JonathanStarup** [comment] 2022-02-16 22:17
Okay! progress:

I renamed test.flix to Test.flix. This changes the file in the system but the "open editors" part of vscode had the test.flix file which persistet even through my reboot. Once i closed this open editor i could restart vscode and the duplication was gone for good.

I cannot seem to replicate that the open editor has the old file, but i can replicate that the duplication error persists if I don't close the editor before restarting vscode. So it seems to me like the actual file on disk and the file open in the editor exist concurrently in Flix.

**Comment by magnus-madsen** [comment] 2022-03-26 09:04
1. VSCode/Operating Systems are retarded. Its a well known limitation that its difficult to monitor for file renames.
2. This is not a bug in Flix, but in the VSCode plugin, so the ticket should be there (but I don't think we can even do anything atm).

**Closed by magnus-madsen** 2022-03-26 09:04 UTC
Labels: bug
