### ISSUE TITLE
Add safe upcast functions?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4248] opened 2022-07-12 12:07 UTC
What if we added:

```
def upcast(f: a -> b): a -> b & ef = x -> f(x) as & ef
```

and used them in places where effect casts are safe? 

- I assume the above signature could be generalized to work with both effect systems?
- I assume we could also have `upcast2`, `upcast3`, as needed.

**Comment by magnus-madsen** [comment] 2022-07-12 12:07
@JonathanStarup Thoughts?

@mlutze Does this solve our problems? Potentially also for Stephen?

**Comment by magnus-madsen** [comment] 2022-07-12 12:11
I think this:

https://github.com/flix/flix/blob/master/main/src/library/List.flix#L652

can then become just `upcast(identity)`.

**Comment by mlutze** [comment] 2022-07-12 12:23
Yes, this looks good. Especially because it requires a pure argument, which should make it safer than a full cast.

**Comment by magnus-madsen** [comment] 2022-07-12 12:30
> Yes, this looks good. Especially because it requires a pure argument, which should make it safer than a full cast.

Can you quickly confirm that it solves "your" problem?

**Comment by JonathanStarup** [comment] 2022-07-12 12:38
I like it, although I think Effect should be included in the name. 

I had a thought that we could make a checked function that can upcast java types so maybe the upcast bucket of names should be left a little open

**Comment by magnus-madsen** [comment] 2022-07-12 12:47
We could consider adding a checked cast expression: `cast e` which transform a into b then post type inference checks whether the casts are sensible.

**Comment by magnus-madsen** [comment] 2022-07-12 12:48
@mlutze If you can confirm this works then Ill ask @jaschdoc to try it out :)

**Comment by magnus-madsen** [comment] 2022-07-12 13:13
I think, assuming Matt gives the greenlight, I would like a two pronged approach:

1. We implement `def upcast(...)` as above and use it as widely as possible in the std. lib. We use this to identify any weaknesses etc.
2. We add a new expression `upcast exp` (`Upcast` after `Cast` in the AST) which has lax typing rules (essentially from `a -> b`). Post typing, e.g. in `Safety` or `Redundancy` we check that the conversion performed by `upcast` is safe. This can then later be extended to deal with e.g. Java subtyping. (We can start with just one rule for say anything non-primitive to Object).

**Comment by mlutze** [comment] 2022-07-12 13:30
Seems to work.

I was unable to reproduce the particular problem with `Nel.reduceRightTo`, (silly Matt, worrying about nothing) so this feature isn't as critical as I had originally thought.

**Comment by magnus-madsen** [comment] 2022-07-12 13:33
Nevertheless, lets get it done. Then we can offer it to Stephen and see how many issue he runs into.

@jaschdoc Will you add the `upcast` function and use it throughout the standard library? (A search for `as & Pure` or `as & ef` should be a good starting point.

**Comment by mlutze** [comment] 2022-07-12 13:52
The standard library type checks in `Xeffects` mode without issue. The problem is some weirdnesses. The one I thought we had with `Nel` is no longer a problem. There's still something with `Traversable.ContStateRight`, where the dual effect system made it into an enum, but that's all private so the end user shouldn't be exposed.

**Comment by stephentetley** [comment] 2022-07-12 16:17
This looks good.

I can have a look at `Traversable.ContStateRight` - I don't think it needs the internal `Impure`.

**Comment by mlutze** [comment] 2022-07-12 17:12
@stephentetley Does this work with the `--Xeffects` flag?

**Comment by stephentetley** [comment] 2022-07-12 18:06
@mlutze It works for me with `--Xeffects` though I'm a day or two off Flix head.

It should be copy/pastable over the end of `Traversable.flix` file.

**Comment by mlutze** [comment] 2022-07-12 20:18
Is it actually unsafe? It seems that the rule "an expression marked as pure will never have an effect" is not violated.

**Comment by magnus-madsen** [comment] 2022-07-12 20:22
I meant `upcast` (its late I guess).

**Comment by magnus-madsen** [comment] 2022-07-12 20:22
@jaschdoc Will you give this priority because then we can unblock the merge of set effects :)

**Comment by JonathanStarup** [comment] 2022-07-13 07:09
> Alright, lets go ahead and add `unsafe` and refactor the standard library.
> 
> @JonathanStarup What consequences will this have for our experiments?

Nothing bad, I think. `as & Pure` would not use this method.

**Comment by magnus-madsen** [comment] 2022-07-13 08:19
> > Alright, lets go ahead and add `unsafe` and refactor the standard library.
> > @JonathanStarup What consequences will this have for our experiments?
> 
> Nothing bad, I think. `as & Pure` would not use this method.

Right, so this is only for safe casts, and we are not counting those?

**Comment by JonathanStarup** [comment] 2022-07-13 09:39
> > > Alright, lets go ahead and add `unsafe` and refactor the standard library.
> > > @JonathanStarup What consequences will this have for our experiments?
> > 
> > Nothing bad, I think. `as & Pure` would not use this method.
> 
> Right, so this is only for safe casts, and we are not counting those?

We are only counting casts to pure which are never safe so yes

**Closed** 2022-07-15 12:52 UTC
Labels: student-programmer, high-priority
