### ISSUE TITLE
Remove (secret) support for implicit regions

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5164] opened 2022-12-21 17:59 UTC

**Comment by magnus-madsen** [comment] 2022-12-23 22:21
@mlutze This happens in `Resolver`, so perhaps best you remove it, given that you have your hands in that code?

**Comment by magnus-madsen** [comment] 2022-12-23 22:22
(You can do it when you feel its the right time).

**Comment by mlutze** [comment] 2023-01-03 07:57
duplicate of #5215

**Closed by mlutze** 2023-01-03 07:57 UTC
