### ISSUE TITLE
Benchmark.flix triggers crash

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7828] opened 2024-06-03 12:22 UTC

**Comment by magnus-madsen** [comment] 2024-06-03 12:22
@mlutze Can you take a look? It used to work. But I guess the file was not under unit testing?

**Comment by mlutze** [comment] 2024-06-03 12:51
That's weird, it's part of the standard library

**Comment by mlutze** [comment] 2024-08-15 07:52
Can't reproduce. Anyway, this is part of a known class of errors where we cannot handle error types. Should be resolved with the new solver.

**Closed by mlutze** 2024-08-15 07:52 UTC
Labels: bug
